services:
  autohls:
    build: .
    container_name: autohls
    restart: unless-stopped
    volumes:
      - /mnt/disks/CacheDrive/recordings:/source
      - /mnt/disks/SlowPhatty/VOD:/dest
    environment:
      - NVIDIA_VISIBLE_DEVICES
      - NVIDIA_DRIVER_CAPABILITIES
      - SOURCE
      - DEST
      - PORT
      - CORSHOST
      - SOCKET_PATH
      - PUBLIC_SOCKET_URL
      - PUBLIC_SOCKET_PATH
    runtime: nvidia
    networks:
      br0:
        ipv4_address: '10.0.3.131'

networks:
  br0:
    external: true
