version: '3'

services:
  autohls:
    build: .
    container_name: autohls
    volumes:
      - /mnt/disks/CacheDrive/recordings:/source
      - /mnt/disks/SlowPhatty/VOD:/dest
    environment:
      - NVIDIA_VISIBLE_DEVICES
      - NVIDIA_DRIVER_CAPABILITIES
      - SOURCE
      - DEST
      - PORT
      - HOST
    runtime: nvidia
    networks:
      br0:
        ipv4_address: '10.0.3.131'

networks:
  br0:
    external:
      name: br0
