export const DefaultRenditions = [
  {
    width: 640,
    height: 360,
    profile: 'high',
    hlsTime: '4',
    bv: '800k',
    maxrate: '856k',
    bufsize: '1200k',
    ba: '96k',
    ts_title: '360p',
    master_title: '360p',
  },
  {
    width: 842,
    height: 480,
    profile: 'high',
    hlsTime: '4',
    bv: '1400k',
    maxrate: '1498',
    bufsize: '2100k',
    ba: '128k',
    ts_title: '480p',
    master_title: '480p',
  },
  {
    width: 1280,
    height: 720,
    profile: 'high',
    hlsTime: '4',
    bv: '2800k',
    maxrate: '2996k',
    bufsize: '4200k',
    ba: '128k',
    ts_title: '720p',
    master_title: '720p',
  },
  {
    width: 1920,
    height: 1080,
    profile: 'high',
    hlsTime: '4',
    bv: '5000k',
    maxrate: '5350k',
    bufsize: '7500k',
    ba: '192k',
    ts_title: '1080p',
    master_title: '1080p',
  },
]

export const DefaultCommands = [
  'run',
  '--rm',
  '-i',
  '--runtime=nvidia',
  '-e',
  'NVIDIA_VISIBLE_DEVICES=GPU-d1ee920a-826c-254d-8535-8be053ba1bbd',
  '-e',
  'NVIDIA_DRIVER_CAPABILITIES=all',
  // '--device=/dev/dri',
  '-v',
  '/mnt/disks/CacheDrive/recordings:/source',
  '-v',
  '/mnt/disks/SlowPhatty/VOD:/dest',
  'jrottenberg/ffmpeg:4.2-nvidia',
  // 'akashisn/ffmpeg:5.0-qsv',
  '-y',
  // '-init_hw_device',
  // 'qsv=qsv:hw',
  '-hwaccel',
  'cuvid',
  '-c:v',
  'h264_cuvid',
  // '-filter_hw_device',
  // 'qsv',
  // '-hwaccel_output_format',
  // 'qsv',
  '-fflags',
  '+discardcorrupt',
  '-analyzeduration',
  '10M',
  '-probesize',
  '32M',
]
